networks:
  inception:

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/mariadb

  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/wordpress

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "443:443"
    networks:
      - inception
    environment:
      - WP_DATABASE=${WP_DATABASE}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - VOLUMES_PATH=${VOLUMES_PATH}
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
      args:
        - WP_DATABASE=${WP_DATABASE}
        - WP_USER=${WP_USER}
        - WP_PASSWORD=${WP_PASSWORD}
        - VOLUMES_PATH=${VOLUMES_PATH}
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - 9000
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WP_DATABASE=${WP_DATABASE}
        - WP_USER=${WP_USER}
        - WP_PASSWORD=${WP_PASSWORD}
        - VOLUMES_PATH=${VOLUMES_PATH}
    environment:
      - WP_DATABASE
      - WP_USER
      - WP_PASSWORD
      - VOLUMES_PATH
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure
