networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wp-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/egeraldo/data/wp-database'
  wp-pages:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/egeraldo/data/wp-pages'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "443:443"
    networks:
      - inception
    environment:
      - WP_DATABASE=${WP_DATABASE}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wp-pages:/var/www/html
      - ./logs/nginx:/var/log/nginx 
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
      args:
        - WP_DATABASE=${WP_DATABASE}
        - WP_USER=${WP_USER}
        - WP_PASSWORD=${WP_PASSWORD}
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - 9000
    volumes:
      - wp-pages:/var/www/html
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WP_DATABASE=${WP_DATABASE}
        - WP_USER=${WP_USER}
        - WP_PASSWORD=${WP_PASSWORD}
    environment:
      - WP_DATABASE
      - WP_USER
      - WP_PASSWORD
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp-database:/var/lib/mysql
    expose:
      - 3306
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
