FROM debian:oldstable

ARG WP_DATABASE
ARG WP_USER
ARG WP_PASSWORD

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install mariadb-client mariadb-server -y

RUN mkdir -p /var/lib/mysql /var/run/mysqld && chmod -R 777 /var/run/mysqld

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY ./conf/init.sh /tmp/init.sh

RUN chown -R mysql:mysql /var/lib/mysql /var/run/mysqld && \
    service mysql start && \
    chmod +x /tmp/init.sh && \
    bash /tmp/init.sh

ENTRYPOINT ["mysqld_safe"]