FROM debian:oldstable

ARG WP_DATABASE
ARG WP_USER
ARG WP_PASSWORD

WORKDIR /var/www/html/

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y php7.4 php-fpm php-mysql mariadb-client wget sendmail

RUN wget -O /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x /usr/local/bin/wp \
	&& wp core download --allow-root --path=/var/www/html

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf
COPY ./conf/php.ini /etc/php/7.4/fpm/php.ini
COPY ./conf/script.sh /tmp/script.sh

RUN mkdir /run/php
RUN chmod +x /tmp/script.sh
RUN chown -R www-data:www-data /var/www/html \
	&& chmod 755 /var/www/html

CMD ["/tmp/script.sh"]